# Generated by Django 2.2.5 on 2020-01-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_table3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table3',
            name='age',
        ),
    ]
